development:
  AWS_KEY: 'XXX'
  AWS_SECRET: 'YYY'
  AWS_BUCKET: 'tech_events_example'
  TWITTER_KEY: 'XXX'
  TWITTER_SECRET: 'YYY'
  MC_API_KEY: '12345'
  MC_LIST_ID: 'ABC'

test:
  AWS_KEY: 'XXX'
  AWS_SECRET: 'YYY'
  AWS_BUCKET: 'tech_events_example'
  TWITTER_KEY: 'XXX'
  TWITTER_SECRET: 'YYY'
  MC_API_KEY: '12345'
  MC_LIST_ID: 'ABC'
