development:
  TWITTER_KEY: 'ayzeniuaMusWs60Qk4SFA'
  TWITTER_SECRET: '7S9bLVZ0REt6oUFCfEnTlWTkMEj2fXtG90on4VGE'
  MC_API_KEY: '13708cb242f955d97d1d729a5002b441-us5'
  MC_LIST_ID: '10c5e3d392'

test:
  TWITTER_KEY: 'ayzeniuaMusWs60Qk4SFA'
  TWITTER_SECRET: '7S9bLVZ0REt6oUFCfEnTlWTkMEj2fXtG90on4VGE'
  MC_API_KEY: '13708cb242f955d97d1d729a5002b441-us5'
  MC_LIST_ID: '10c5e3d392'